<?php

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
        'key'      => 'group_about_page_settings',
        'title'    => 'About Page Settings',
        'fields'   => array(
            array(
                'key'   => 'field_about_breadcrumb_home',
                'label' => 'Breadcrumb Home Text',
                'name'  => 'about_breadcrumb_home',
                'type'  => 'text',
                'default_value' => 'الرئيسية',
            ),
            array(
                'key'   => 'field_about_breadcrumb_home_link',
                'label' => 'Breadcrumb Home Link',
                'name'  => 'about_breadcrumb_home_link',
                'type'  => 'url',
                'default_value' => home_url('/'),
            ),
            array(
                'key'   => 'field_about_breadcrumb_current',
                'label' => 'Breadcrumb Current Text',
                'name'  => 'about_breadcrumb_current',
                'type'  => 'text',
                'default_value' => 'من نحن',
            ),
            array(
                'key'   => 'field_about_page_title',
                'label' => 'Page Title (H1)',
                'name'  => 'about_page_title',
                'type'  => 'text',
                'default_value' => 'من نحن',
            ),
            array(
                'key'   => 'field_about_subtitle',
                'label' => 'Subtitle/Subheading',
                'name'  => 'about_subtitle',
                'type'  => 'text',
                'default_value' => 'نؤمن أن كل فكرة تستحق تنفيذًا يليق بها.',
            ),
            array(
                'key'   => 'field_about_eyebrow',
                'label' => 'Eyebrow Text',
                'name'  => 'about_eyebrow',
                'type'  => 'text',
                'default_value' => 'جواهر الشام',
            ),
            array(
                'key'   => 'field_about_heading_primary',
                'label' => 'Heading - Primary Text',
                'name'  => 'about_heading_primary',
                'type'  => 'text',
                'default_value' => 'نمنح أفكارك',
            ),
            array(
                'key'   => 'field_about_heading_secondary',
                'label' => 'Heading - Secondary Text',
                'name'  => 'about_heading_secondary',
                'type'  => 'text',
                'default_value' => 'حضورًا ملموسًا',
            ),
            array(
                'key'   => 'field_about_description_1',
                'label' => 'Description 1',
                'name'  => 'about_description_1',
                'type'  => 'textarea',
                'rows'  => 4,
                'default_value' => 'في جواهر الشام نقدم حلول الطباعة والدعاية، من بطاقات الأعمال والبروشورات والكتالوجات إلى اللوحات والبنرات وأعمال الإكريليك.',
            ),
            array(
                'key'   => 'field_about_description_2',
                'label' => 'Description 2',
                'name'  => 'about_description_2',
                'type'  => 'textarea',
                'rows'  => 4,
                'default_value' => 'نبدأ بفهم احتياجك وطريقة استخدام المطبوع، ثم نراجع معك المواصفات والخامة والتشطيب، لتكون التفاصيل واضحة قبل التنفيذ.',
            ),
            array(
                'key'   => 'field_about_features',
                'label' => 'Features List',
                'name'  => 'about_features',
                'type'  => 'repeater',
                'button_label' => 'Add Feature',
                'sub_fields' => array(
                    array(
                        'key'   => 'field_feature_title',
                        'label' => 'Feature Title',
                        'name'  => 'feature_title',
                        'type'  => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key'   => 'field_feature_description',
                        'label' => 'Feature Description',
                        'name'  => 'feature_description',
                        'type'  => 'textarea',
                        'rows'  => 3,
                        'required' => 1,
                    ),
                ),
                'min' => 1,
            ),
            array(
                'key'   => 'field_about_cta_button_text',
                'label' => 'CTA Button Text',
                'name'  => 'about_cta_button_text',
                'type'  => 'text',
                'default_value' => 'استعرض نماذجنا',
            ),
            array(
                'key'   => 'field_about_cta_button_link',
                'label' => 'CTA Button Link URL',
                'name'  => 'about_cta_button_link',
                'type'  => 'url',
                'default_value' => 'works.html',
            ),
            array(
                'key'   => 'field_about_image',
                'label' => 'About Image',
                'name'  => 'about_image',
                'type'  => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'instructions' => 'Upload an image for the about section.',
            ),
            array(
                'key'   => 'field_about_image_alt',
                'label' => 'About Image Alt Text',
                'name'  => 'about_image_alt',
                'type'  => 'text',
                'default_value' => 'مجموعة منتجات الطباعة',
            ),
            array(
                'key'   => 'field_about_eyebrow_values',
                'label' => 'Values Section Eyebrow',
                'name'  => 'about_eyebrow_values',
                'type'  => 'text',
                'default_value' => 'ما نهتم به',
            ),
            array(
                'key'   => 'field_about_values_title',
                'label' => 'Values Section Title',
                'name'  => 'about_values_title',
                'type'  => 'text',
                'default_value' => 'تفاصيل صغيرة، تصنع الفرق',
            ),
            array(
                'key'   => 'field_about_values',
                'label' => 'Values List',
                'name'  => 'about_values',
                'type'  => 'repeater',
                'button_label' => 'Add Value',
                'sub_fields' => array(
                    array(
                        'key'   => 'field_value_number',
                        'label' => 'Order Number',
                        'name'  => 'value_number',
                        'type'  => 'text',
                        'default_value' => '01',
                        'instructions' => 'e.g., 01, 02, 03',
                    ),
                    array(
                        'key'   => 'field_value_title',
                        'label' => 'Value Title',
                        'name'  => 'value_title',
                        'type'  => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key'   => 'field_value_description',
                        'label' => 'Value Description',
                        'name'  => 'value_description',
                        'type'  => 'textarea',
                        'rows'  => 3,
                        'required' => 1,
                    ),
                ),
            ),
            array(
                'key'   => 'field_about_services_section_title',
                'label' => 'Services Section Title',
                'name'  => 'about_services_section_title',
                'type'  => 'text',
                'default_value' => 'حلول متكاملة للطباعة والدعاية',
            ),
            array(
                'key'   => 'field_about_services',
                'label' => 'Services List',
                'name'  => 'about_services',
                'type'  => 'repeater',
                'button_label' => 'Add Service',
                'sub_fields' => array(
                    array(
                        'key'   => 'field_service_number',
                        'label' => 'Service Number/Icon',
                        'name'  => 'service_number',
                        'type'  => 'text',
                        'default_value' => '▤',
                        'instructions' => 'e.g., ▤, ◇, ▣, ▱',
                    ),
                    array(
                        'key'   => 'field_service_title',
                        'label' => 'Service Title',
                        'name'  => 'service_title',
                        'type'  => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key'   => 'field_service_description',
                        'label' => 'Service Description',
                        'name'  => 'service_description',
                        'type'  => 'textarea',
                        'rows'  => 3,
                        'required' => 1,
                    ),
                ),
            ),
            array(
                'key'   => 'field_about_final_cta_title',
                'label' => 'Final CTA Title',
                'name'  => 'about_final_cta_title',
                'type'  => 'text',
                'default_value' => 'عندك مشروع مشابه؟',
            ),
            array(
                'key'   => 'field_about_final_cta_description',
                'label' => 'Final CTA Description',
                'name'  => 'about_final_cta_description',
                'type'  => 'textarea',
                'rows'  => 3,
                'default_value' => 'خلّنا نطبع فكرتك ونحوّلها إلى واقع مميز.',
            ),
            array(
                'key'   => 'field_about_final_cta_button_text',
                'label' => 'Final CTA Button Text',
                'name'  => 'about_final_cta_button_text',
                'type'  => 'text',
                'default_value' => 'اطلب عرض سعر',
            ),
            array(
                'key'   => 'field_about_final_cta_button_link',
                'label' => 'Final CTA Button Link URL',
                'name'  => 'about_final_cta_button_link',
                'type'  => 'url',
                'default_value' => 'contact.html',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param'    => 'page',
                    'operator' => '==',
                    'value'    => '15',
                ),
            ),
        ),
    ));
}
