<?php

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
        'key'      => 'group_contactus_page_settings',
        'title'    => 'Contact Us Page Settings',
        'fields'   => array(
            array(
                'key'   => 'field_contactus_breadcrumb_home',
                'label' => 'Breadcrumb Home Text',
                'name'  => 'contactus_breadcrumb_home',
                'type'  => 'text',
                'default_value' => 'الرئيسية',
            ),
            array(
                'key'   => 'field_contactus_breadcrumb_home_link',
                'label' => 'Breadcrumb Home Link',
                'name'  => 'contactus_breadcrumb_home_link',
                'type'  => 'url',
                'default_value' => home_url('/'),
            ),
            array(
                'key'   => 'field_contactus_breadcrumb_current',
                'label' => 'Breadcrumb Current Text',
                'name'  => 'contactus_breadcrumb_current',
                'type'  => 'text',
                'default_value' => 'تواصل معنا',
            ),
            array(
                'key'   => 'field_contactus_page_title',
                'label' => 'Page Title (H1)',
                'name'  => 'contactus_page_title',
                'type'  => 'text',
                'default_value' => 'تواصل معنا',
            ),
            array(
                'key'   => 'field_contactus_subtitle',
                'label' => 'Page Subtitle',
                'name'  => 'contactus_subtitle',
                'type'  => 'text',
                'default_value' => 'مشروعك القادم يبدأ بمحادثة. شاركنا فكرتك، ولنحدد معك التفاصيل.',
            ),
            array(
                'key'   => 'field_contactus_eyebrow',
                'label' => 'Contact Section Eyebrow',
                'name'  => 'contactus_eyebrow',
                'type'  => 'text',
                'default_value' => 'يسعدنا تواصلك',
            ),
            array(
                'key'   => 'field_contactus_title_primary',
                'label' => 'Contact Section Title - Primary',
                'name'  => 'contactus_title_primary',
                'type'  => 'text',
                'default_value' => 'لنطبع فكرتك القادمة',
            ),
            array(
                'key'   => 'field_contactus_title_secondary',
                'label' => 'Contact Section Title - Secondary',
                'name'  => 'contactus_title_secondary',
                'type'  => 'text',
                'default_value' => '',
            ),
            array(
                'key'   => 'field_contactus_description',
                'label' => 'Contact Section Description',
                'name'  => 'contactus_description',
                'type'  => 'textarea',
                'rows'  => 4,
                'default_value' => 'حدد الخدمة والمقاس والكمية والتشطيب إن أمكن، لنفهم احتياجك بصورة أوضح.',
            ),
            array(
                'key'   => 'field_contactus_phone_label',
                'label' => 'Phone Label',
                'name'  => 'contactus_phone_label',
                'type'  => 'text',
                'default_value' => 'اتصل بنا',
            ),
            array(
                'key'   => 'field_contactus_phone_number',
                'label' => 'Phone Number',
                'name'  => 'contactus_phone_number',
                'type'  => 'text',
                'default_value' => '+966 53 244 6558',
            ),
            array(
                'key'   => 'field_contactus_phone_link',
                'label' => 'Phone Link URL',
                'name'  => 'contactus_phone_link',
                'type'  => 'url',
                'default_value' => 'tel:+966532446558',
            ),
            array(
                'key'   => 'field_contactus_address_label',
                'label' => 'Address Label',
                'name'  => 'contactus_address_label',
                'type'  => 'text',
                'default_value' => 'موقعنا',
            ),
            array(
                'key'   => 'field_contactus_address_text',
                'label' => 'Address Text',
                'name'  => 'contactus_address_text',
                'type'  => 'text',
                'default_value' => 'الرياض — حي المنصورة',
            ),
            array(
                'key'   => 'field_contactus_map_link',
                'label' => 'Map Search Link',
                'name'  => 'contactus_map_link',
                'type'  => 'url',
                'default_value' => 'https://www.google.com/maps/search/?api=1&query=جواهر+الشام+الرياض+المنصورة',
            ),
            array(
                'key'   => 'field_contactus_map_link_text',
                'label' => 'Map Link Text',
                'name'  => 'contactus_map_link_text',
                'type'  => 'text',
                'default_value' => 'البحث عن الموقع على الخريطة',
            ),
            array(
                'key'   => 'field_contactus_whatsapp_label',
                'label' => 'WhatsApp Label',
                'name'  => 'contactus_whatsapp_label',
                'type'  => 'text',
                'default_value' => 'واتساب',
            ),
            array(
                'key'   => 'field_contactus_whatsapp_link',
                'label' => 'WhatsApp Link URL',
                'name'  => 'contactus_whatsapp_link',
                'type'  => 'url',
                'default_value' => 'https://wa.me/966532446558',
            ),
            array(
                'key'   => 'field_contactus_whatsapp_button_text',
                'label' => 'WhatsApp Button Text',
                'name'  => 'contactus_whatsapp_button_text',
                'type'  => 'text',
                'default_value' => 'ابدأ محادثة',
            ),
            array(
                'key'   => 'field_contactus_form_title',
                'label' => 'Form Title',
                'name'  => 'contactus_form_title',
                'type'  => 'text',
                'default_value' => 'اطلب عرض سعر',
            ),
            array(
                'key'   => 'field_contactus_service_options',
                'label' => 'Service Options',
                'name'  => 'contactus_service_options',
                'type'  => 'repeater',
                'button_label' => 'Add Service Option',
                'sub_fields' => array(
                    array(
                        'key'   => 'field_service_option_text',
                        'label' => 'Service Option Text',
                        'name'  => 'service_text',
                        'type'  => 'text',
                        'required' => 1,
                    ),
                ),
                'instructions' => 'Service options shown in the contact form dropdown.',
            ),
            array(
                'key'   => 'field_contactus_form_note',
                'label' => 'Form Note Text',
                'name'  => 'contactus_form_note',
                'type'  => 'text',
                'default_value' => 'نجهّز تفاصيلك في رسالة واتساب، وتراجعها قبل إرسالها.',
            ),
            array(
                'key'   => 'field_contactus_form_button_text',
                'label' => 'Form Submit Button Text',
                'name'  => 'contactus_form_button_text',
                'type'  => 'text',
                'default_value' => 'تجهيز الطلب عبر واتساب',
            ),
            array(
                'key'   => 'field_contactus_whatsapp_link_template',
                'label' => 'WhatsApp Link Template (JavaScript)',
                'name'  => 'contactus_whatsapp_template',
                'type'  => 'textarea',
                'rows'  => 5,
                'default_value' => 'https://wa.me/966532446558?text=مرحبًا جواهر الشام، أود طلب عرض سعر.\nالاسم: ${name}\nرقم الجوال: ${phone}\nالخدمة: ${service}\nتفاصيل الطلب: ${message}',
                'instructions' => 'Template variables: ${name}, ${phone}, ${service}, ${message}',
            ),
            array(
                'key'   => 'field_contactus_ready_button_text',
                'label' => 'WhatsApp Ready Button Text',
                'name'  => 'contactus_ready_button_text',
                'type'  => 'text',
                'default_value' => 'فتح واتساب وإكمال الإرسال',
            ),
            array(
                'key'   => 'field_contactus_status_message',
                'label' => 'Status Message Text',
                'name'  => 'contactus_status_message',
                'type'  => 'text',
                'default_value' => 'تم تجهيز رسالتك. اضغط «فتح واتساب» لإكمال الإرسال.',
            ),
            array(
                'key'   => 'field_contactus_background_image',
                'label' => 'Background Image',
                'name'  => 'contactus_background_image',
                'type'  => 'image',
                'return_format' => 'url',
                'preview_size'  => 'full',
            ),
            array(
                'key'   => 'field_contactus_background_color',
                'label' => 'Background Color (fallback)',
                'name'  => 'contactus_background_color',
                'type'  => 'color',
                'default_value' => '#ffffff',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param'    => 'page',
                    'operator' => '==',
                    'value'    => '46',
                ),
            ),
        ),
    ));
}
