<?php

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
        'key'      => 'group_works_page_settings',
        'title'    => 'Works Page Settings',
        'fields'   => array(
            array(
                'key'   => 'field_works_page_title',
                'label' => 'Page Title (H1)',
                'name'  => 'works_page_title',
                'type'  => 'text',
                'default_value' => 'أعمالنا',
            ),
            array(
                'key'   => 'field_works_breadcrumb_home',
                'label' => 'Breadcrumb Home Text',
                'name'  => 'works_breadcrumb_home',
                'type'  => 'text',
                'default_value' => 'الرئيسية',
            ),
            array(
                'key'   => 'field_works_breadcrumb_home_link',
                'label' => 'Breadcrumb Home Link',
                'name'  => 'works_breadcrumb_home_link',
                'type'  => 'url',
                'default_value' => home_url('/'),
            ),
            array(
                'key'   => 'field_works_breadcrumb_current',
                'label' => 'Breadcrumb Current Text',
                'name'  => 'works_breadcrumb_current',
                'type'  => 'text',
                'default_value' => 'أعمالنا',
            ),
            array(
                'key'   => 'field_works_description',
                'label' => 'Description',
                'name'  => 'works_description',
                'type'  => 'textarea',
                'rows'  => 4,
                'default_value' => 'تفاصيل متنوعة، وهوية تطبع أثرها. استعرض نماذج المطبوعات والدعاية من بروفايل جواهر الشام.',
            ),
            array(
                'key'   => 'field_works_filters_title',
                'label' => 'Filters Section Title',
                'name'  => 'works_filters_title',
                'type'  => 'text',
                'default_value' => 'تصفية الأعمال',
            ),
            array(
                'key'   => 'field_works_filters',
                'label' => 'Filter Buttons',
                'name'  => 'works_filters',
                'type'  => 'repeater',
                'button_label' => 'Add Filter',
                'sub_fields' => array(
                    array(
                        'key'   => 'field_filter_label',
                        'label' => 'Filter Label',
                        'name'  => 'label',
                        'type'  => 'text',
                        'required' => 1,
                        'default_value' => 'الكل',
                    ),
                    array(
                        'key'   => 'field_filter_value',
                        'label' => 'Filter Value (data attribute)',
                        'name'  => 'value',
                        'type'  => 'text',
                        'required' => 1,
                        'default_value' => 'الكل',
                        'instructions' => 'e.g., الكل, ورقيات, لوحات, إكريليك, تغليف, هدايا',
                    ),
                    array(
                        'key'   => 'field_filter_is_active',
                        'label' => 'Is Active (default)',
                        'name'  => 'is_active',
                        'type'  => 'true_false',
                        'ui'         => 1,
                    ),
                ),
                'min' => 1,
            ),
            array(
                'key'   => 'field_works_gallery_title',
                'label' => 'Gallery Section Title',
                'name'  => 'works_gallery_title',
                'type'  => 'text',
                'default_value' => '',
                'instructions' => 'Optional: Add a title for the gallery section.',
            ),
            array(
                'key'   => 'field_works_gallery_note',
                'label' => 'Gallery Note Text',
                'name'  => 'works_gallery_note',
                'type'  => 'text',
                'default_value' => 'صور ونماذج توضيحية من البروفايل.',
            ),
            array(
                'key'   => 'field_works_gallery_note_class',
                'label' => 'Gallery Note CSS Class',
                'name'  => 'works_gallery_note_class',
                'type'  => 'text',
                'default_value' => 'center muted',
            ),
            array(
                'key'   => 'field_works_items',
                'label' => 'Works Items',
                'name'  => 'works_items',
                'type'  => 'repeater',
                'button_label' => 'Add Work Item',
                'sub_fields' => array(
                    array(
                        'key'   => 'field_work_item_title',
                        'label' => 'Work Title',
                        'name'  => 'title',
                        'type'  => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key'   => 'field_work_item_image',
                        'label' => 'Work Image',
                        'name'  => 'image',
                        'type'  => 'image',
                        'return_format' => 'url',
                        'preview_size'  => 'medium',
                        'required' => 1,
                        'instructions' => 'Upload the work/portfolio image.',
                    ),
                    array(
                        'key'   => 'field_work_item_image_alt',
                        'label' => 'Image Alt Text',
                        'name'  => 'image_alt',
                        'type'  => 'text',
                        'instructions' => 'Alt text for accessibility and SEO.',
                    ),
                    array(
                        'key'   => 'field_work_item_description',
                        'label' => 'Work Description',
                        'name'  => 'description',
                        'type'  => 'textarea',
                        'rows'  => 3,
                        'required' => 1,
                    ),
                    array(
                        'key'   => 'field_work_item_category',
                        'label' => 'Category (for filter)',
                        'name'  => 'category',
                        'type'  => 'select',
                        'choices' => array(
                            'الكل' => 'الكل',
                            'ورقيات' => 'ورقيات',
                            'لوحات' => 'لوحات',
                            'إكريليك' => 'إكريليك',
                            'تغليف' => 'تغليف',
                            'هدايا' => 'هدايا',
                        ),
                        'default_value' => 'ورقيات',
                        'allow_null' => 0,
                        'ui' => 1,
                        'instructions' => 'Select the category this work belongs to. This is used for gallery filtering.',
                    ),
                    array(
                        'key'   => 'field_work_item_lightbox_title',
                        'label' => 'Lightbox Title',
                        'name'  => 'lightbox_title',
                        'type'  => 'text',
                        'default_value' => 'تفاصيل العمل',
                    ),
                ),
            ),
            array(
                'key'   => 'field_works_final_cta_title',
                'label' => 'Final CTA Title',
                'name'  => 'works_final_cta_title',
                'type'  => 'text',
                'default_value' => 'عندك مشروع مشابه؟',
            ),
            array(
                'key'   => 'field_works_final_cta_description',
                'label' => 'Final CTA Description',
                'name'  => 'works_final_cta_description',
                'type'  => 'textarea',
                'rows'  => 3,
                'default_value' => 'خلّنا نطبع فكرتك ونحوّلها إلى واقع مميز.',
            ),
            array(
                'key'   => 'field_works_final_cta_button_text',
                'label' => 'Final CTA Button Text',
                'name'  => 'works_final_cta_button_text',
                'type'  => 'text',
                'default_value' => 'اطلب عرض سعر',
            ),
            array(
                'key'   => 'field_works_final_cta_button_link',
                'label' => 'Final CTA Button Link URL',
                'name'  => 'works_final_cta_button_link',
                'type'  => 'url',
                'default_value' => 'contact.html',
            ),
            array(
                'key'   => 'field_works_lightbox_title_text',
                'label' => 'Lightbox Dialog Title',
                'name'  => 'works_lightbox_title_text',
                'type'  => 'text',
                'default_value' => 'تفاصيل العمل',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param'    => 'page',
                    'operator' => '==',
                    'value'    => '22',
                ),
            ),
        ),
    ));
}
